enable-magisk-update = true
parallel-jobs = 1
remove-rv-integrations-checks = true

[proton-mail-revanced]
enabled = false
app-name = "proton-mail"
rv-brand = "revanced"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonmail.android"

[samsung-radio-revanced]
enabled = false
app-name = "samsung-radio"
rv-brand = "revanced"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://samsung-radio.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/samsung-electronics-co-ltd/samsung-radio/"
archive-dlurl = "https://archive.org/download/geologically/apks/com.sec.android.app.fm"

[lightroom-revanced]
enabled = false
app-name = "lightroom"
rv-brand = "revanced"
arch = "arm64-v8a"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
# uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
archive-dlurl = "https://archive.org/download/geologically/apks/com.adobe.lrmobile"

[duolingo-revanced]
enabled = false
app-name = "duolingo"
rv-brand = "revanced"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/duolingo/duolingo-duolingo"
archive-dlurl = "https://archive.org/download/geologically/apks/com.duolingo"

[twitch-revanced]
enabled = false
app-name = "twitch"
rv-brand = "revanced"
version = "25.3.0"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch"
# archive-dlurl = "https://archive.org/download/geologically/apks/tv.twitch.android.app"

[twitter-revanced]
enabled = false
app-name = "twitter"
rv-brand = "revanced"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"

[tiktok-revanced]
enabled = false
app-name = "tiktok"
rv-brand = "revanced"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
archive-dlurl = "https://archive.org/download/geologically/apks/com.zhiliaoapp.musically"

[soundcloud-revanced]
enabled = false
app-name = "soundcloud"
rv-brand = "revanced"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud"

[youtube-anddea-nord]
enabled = false
app-name = "youtube"
rv-brand = "anddea-nord"
build-mode = "both"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
included-patches = "'MaterialYou'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#2E3440 -OlightThemeBackgroundColor=#E5E9F0"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-anddea-nord]
enabled = false
app-name = "youtube-music"
rv-brand = "anddea-nord"
build-mode = "both"
arch = "both"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=#2E3440 -OmaterialYou=#5E81AC"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[youtube-anddea-mocha]
enabled = false
app-name = "youtube"
rv-brand = "anddea-mocha"
build-mode = "both"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
included-patches = "'MaterialYou'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#FF181825 -OlightThemeBackgroundColor=#E6E9EF"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-anddea-mocha]
enabled = false
app-name = "youtube-music"
rv-brand = "anddea-mocha"
build-mode = "both"
arch = "both"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=#FF181825 -OmaterialYou=#89B4FA"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[youtube-morphe-nord]
enabled = true
app-name = "youtube"
rv-brand = "morphe-nord"
build-mode = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#2E3440 -OlightThemeBackgroundColor=#E5E9F0"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-morphe-mocha]
enabled = true
app-name = "youtube"
rv-brand = "morphe-mocha"
build-mode = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#FF181825 -OlightThemeBackgroundColor=#E6E9EF"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"
