parallel-jobs = 1
patches-version = "dev"
enable-magisk-update = false
remove-rv-integrations-checks = true

[youtube-anddea-nord]
enabled = false
app-name = "youtube"
rv-brand = "anddea-nord"
build-mode = "apk"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
included-patches = "'MaterialYou'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#2E3440"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-anddea-nord]
enabled = false
app-name = "youtube-music"
rv-brand = "anddea-nord"
build-mode = "apk"
arch = "both"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=#2E3440 -OmaterialYou=#5E81AC"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[youtube-anddea-mocha]
enabled = false
app-name = "youtube"
rv-brand = "anddea-mocha"
build-mode = "both"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
included-patches = "'MaterialYou'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#FF181825"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-anddea-mocha]
enabled = false
app-name = "youtube-music"
rv-brand = "anddea-mocha"
build-mode = "both"
arch = "both"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=#FF181825 -OmaterialYou=#89B4FA"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[youtube-morphe-nord]
enabled = false
app-name = "youtube"
rv-brand = "morphe-nord"
build-mode = "apk"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#2E3440 -OlightThemeBackgroundColor=#E6E9EF"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-morphe-nord]
enabled = false
app-name = "youtube-music"
rv-brand = "morphe-nord"
build-mode = "apk"
arch = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=#2E3440"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[youtube-morphe-exp]
enabled = false
app-name = "youtube"
rv-brand = "morphe-exp"
build-mode = "both"
version = "latest"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[twitter-piko-materialu]
enabled = false 
app-name = "twitter"
rv-brand = "piko-materialu"
arch = "both"
patches-source = "crimera/piko"
included-patches = "'Bring back twitter' 'Dynamic color'"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
dpi = "120-640dpi 480dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"

[google-photos-revanced]
enabled = true
app-name = "google-photos"
rv-brand = "revanced"
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"

[reddit-morphe]
enabled = true
app-name = "reddit"
rv-brand = "morphe"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"
